branches:
  except:
    - /^legacy\/.*$/
    - heroku
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  global:
    - APP_ENV='testing'
  matrix:
    - DB="pgsql" REPO=$TRAVIS_BUILD_DIR/"public/resources/default/" REPO_TYPE="local"
    - DB="mysql" REPO=$TRAVIS_BUILD_DIR/"public/resources/default/" REPO_TYPE="local"
    - DB="pgsql" REPO="http://technic.pagefortress.com/mods/" REPO_TYPE="remote"
    - DB="mysql" REPO="http://technic.pagefortress.com/mods/" REPO_TYPE="remote"
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
sudo: false
before_install:
  - pwd
  - echo $REPO
  - composer self-update
install: travis_retry composer install --prefer-source --no-interaction
before_script:
  - php artisan env
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS solder;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database solder;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS solder;'; fi"
  - php artisan migrate:install
  - php artisan migrate
  - php artisan db:seed --class="TestSeeder"
script: vendor/bin/phpunit --verbose
